### ISSUE TITLE
docker-compose 적용

### ISSUE THREAD

**Issue by Wooin-dev** [Wooin-dev/dailyone_server#27]
[컨테이너간 통신](https://velog.io/@seoyunjang/7.-%EC%BB%A8%ED%85%8C%EC%9D%B4%EB%84%88%EA%B0%84-%ED%86%B5%EC%8B%A0)

**Comment by Wooin-dev** [comment]
#### docker-compose.yaml

위치 : /data/DOCKER
```
version: '3.8'
services:

  web:
    container_name: dailyone-web
    image: donedev/dailyone-web
    expose:
      - 3000
    ports:
      - 3000:3000

  server:
    container_name: dailyone-server
    image: donedev/dailyone-server
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./conf/:/etc/nginx/conf.d
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - server
```
